### ISSUE TITLE
Transfosmar o readme.md em Markdown

### ISSUE THREAD

**Issue by tomazcunha** [Mateus-msj3/Python_Youtube_Download#2]
Seria interessante tentar transformar em Markdown para ficar no padrão da maioria dos readme.md, e retirar essas tags html.

**Comment by Mateus-msj3** [comment]
Ok. Só que ainda não tive tempo pra aprender escrever os readme em markdown. Se pude ajudar, agradeço desde já.

**Comment by tomazcunha** [comment]
Eu ia escrever mas, preferir mandar primeiro a correção.
